#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/spacewalk" ]; then
        update-rc.d spacewalk defaults >/dev/null
        invoke-rc.d spacewalk start || exit $?
fi
# End automatically added section
