#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/spacewalk" ]; then
        invoke-rc.d spacewalk stop || exit $?
        update-rc.d spacewalk remove >/dev/null
fi
# End automatically added section
