#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
        if [ -x "/etc/init.d/spacewalk" ]; then
                update-rc.d spacewalk stop >/dev/null || true
        fi
fi
# End automatically added section
